Fix MessageListener not passing type parameter
leancodepl/comms pull request #40
Opened 2022-10-18 16:10 UTC by iasiu

* Bump comms

* Add type parameter Message to MessageListener state

Fixes #39

2022-10-18 16:18 UTC, bartekpacia reviewed
changelog update?

2022-10-18 16:19 UTC, PiotrRogulski requested changes
Also bump package version

2022-10-19 14:17 UTC, bartekpacia commented on packages/flutter_comms/CHANGELOG.md
> +- Fix MessageListener type parameter
```suggestion
- Fix `MessageListener` type parameter (#40)
```

2022-10-19 14:52 UTC, bartekpacia approved these changes

2022-10-19 15:07 UTC, PiotrRogulski approved these changes

2022-10-19 15:13 UTC, merged